# Generated by Django 3.0.2 on 2020-02-24 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200225_0041'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CUser',
        ),
    ]
