# Generated by Django 3.0.2 on 2020-02-25 13:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200225_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='api_key',
            field=models.CharField(blank=True, db_column='api_key', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='counter',
            field=models.IntegerField(db_column='counter', default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='dateOfkey',
            field=models.DateTimeField(db_column='dateOfkey', default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
