# Generated by Django 3.0.2 on 2020-02-25 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20200225_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='quotas',
            field=models.IntegerField(db_column='quotas', default=1),
        ),
    ]
