# Generated by Django 3.0.2 on 2020-02-25 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_user_quotas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='userid',
        ),
        migrations.AlterField(
            model_name='user',
            name='loginname',
            field=models.CharField(db_column='LoginName', max_length=40, primary_key=True, serialize=False),
        ),
    ]
